logsBucket: "gs://portfolio-jakub-rejch-cloudbuild-logs"

steps:
  # budowanie obrazu dockera
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/portfolio-jakub-rejch/react-app/react-app-image:$COMMIT_SHA'
      - '.'
    env:
      - 'REACT_APP_API_URL=https://bk-app-be.onrender.com/api/portfolio/v1'
      - 'REACT_APP_ADD_SKILL=/add/skill'
      - 'REACT_APP_GET_SKILLS=/get-skills'
      - 'REACT_APP_LOGIN=/login'
      - 'REACT_APP_VERIFY=/auth'
    # wypychanie obrazu do Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/portfolio-jakub-rejch/react-app/react-app-image:$COMMIT_SHA'
    # Wdrozenie aplikacji w Cloud Run (GREEN)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        if gcloud run services describe react-app-green --platform=managed --region=us-central1; then
          echo "Service exists, deploying with --no-traffic"
          gcloud run deploy react-app-green \
            --image=us-central1-docker.pkg.dev/portfolio-jakub-rejch/react-app/react-app-image:$COMMIT_SHA \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --no-traffic
        else
          echo "Service does not exist, deploying without --no-traffic"
          gcloud run deploy react-app-green \
            --image=us-central1-docker.pkg.dev/portfolio-jakub-rejch/react-app/react-app-image:$COMMIT_SHA \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
        fi
    # sprawdzenie czy nowa wersja działa poprawnie (Testowanie endpointu /health)
  - name: 'curlimages/curl'
    args:
      - 'f'
      - 'https://react-app-green<region>.a.run.app/index.html'
    timeout: '10s'
    allowFailure: true

    # Jeśli testy się powiodą, przełącz ruch na nową wersję
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'react-app'
      - '--region=us-central1'
      - '--to-latest'
images:
  - 'us-central1-docker.pkg.dev/portfolio-jakub-rejch/react-app/react-app-image:$COMMIT_SHA'