logsBucket: "gs://portfolio-jakub-rejch-cloudbuild-logs"

steps:
  # budowanie obrazu dockera
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/portfolio-jakub-rejch/react-app/react-app-image'
      - '.'
    # wypychanie obrazu do Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/portfolio-jakub-rejch/react-app/react-app-image'
    # Wdrozenie aplikacji w Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'react-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/portfolio-jakub-rejch/react-app/react-app-image'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/portfolio-jakub-rejch/react-app/react-app-image'